services:
  redis:
    image: redis:6
    ports:
      - '6379:6379'
    volumes:
      - green-redis:/var/lib/redis/data

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    links:
      - redis
    env_file:
      - .env

  web:
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
    build:
      context: .
      args:
        - BUILD_ENV=production
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
    command: rails server -b 0.0.0.0 -P /dev/null
    links:
      - redis
    env_file:
      - .env

volumes:
  green-redis: