name: set-environment
description: 'Set environment variables for the action'
inputs:
  secret-token:
    description: 'Secret token'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        touch .env
        echo SECRET_TOKEN=${{ inputs.secret-token }} >> .env
        cat .env
      shell: bash