name: set-environment
description: 'Set environment variables for the action'
runs:
  using: "composite"
  steps:
    - run: |
        touch .env
        echo SECRET_TOKEN=${{ secrets.SECRET_TOKEN }} >> .env
        echo CACHE_URL=${{ secrets.CACHE_URL }} >> .env
        echo JOB_WORKER_URL=${{ secrets.JOB_WORKER_URL }} >> .env
        cat .env
      shell: bash