name: deploy
on:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./set-environment.yml
      - name: Build Docker image
        run: docker-compose -f docker-compose.dev.yml build
      - name: Execute tests
        run: docker-compose -f docker-compose.dev.yml run -e "RAILS_ENV=test" web rake test
  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd green
            git checkout main
            git pull
            docker-compose -f docker-compose.prod.yml build
            sudo systemctl restart green.service
