name: run-tests
on: [ pull_request ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute tests
        run: docker-compose -f docker-compose.dev.yml run -e "RAILS_ENV=test" web rake test
